#include <haard/ast_query/ast_query.h>
#include <haard/emitter/emitter.h>

using namespace haard;

// the thirteen builtins as C++ writes them. 'char' is the language's own and
// not a stand-in for i8, so it stays 'char'
static const char* BUILTIN_CPP[] = {
    "uint8_t", "uint16_t", "uint32_t", "uint64_t",
    "int8_t", "int16_t", "int32_t", "int64_t",
    "float", "double", "bool", "void", "char"
};

Emitter::Emitter() {
    compilation = nullptr;
    indentation = 0;
}

void Emitter::set_compilation(Compilation* compilation) {
    this->compilation = compilation;
}

const std::string& Emitter::get_error() {
    return error;
}

void Emitter::fail(const std::string& message) {
    // the first reason is the one that is true; everything after it is a
    // consequence of having stopped
    if (error.size() == 0) {
        error = message;
    }
}

// A generic declaration is not a class, it is what one is made from: record
// 0002 turns every use of it into a clone, and the clones are what the program
// is written in terms of. Emitting the original too would write C++ naming
// type parameters nothing bound.
//
// A clone has the parameters in its tree as well -- it is a copy -- so the
// question is not whether they are there but whether this declaration is one
// the source wrote
bool Emitter::is_generic(u32 module_index, u32 declaration) {
    Module* module = compilation->get_module(module_index);
    AstQuery query;

    query.set_module(module);

    if (query.get_generic_parameters(declaration).size() == 0) {
        return false;
    }

    u32 candidate = module->get_symbols()->candidate_of(declaration);

    return candidate == 0 || module->get_instantiation(candidate) == nullptr;
}

bool Emitter::emit(std::ostream& stream) {
    out.str("");
    error.clear();
    indentation = 0;
    emitted.clear();
    emitting.clear();

    if (compilation->get_module_count() == 0) {
        fail("nothing to emit");
        return false;
    }

    out << "// generated by hdc -- do not edit\n";
    out << "#include <cstdint>\n";

    // record 0030: the six native functions of 'std.io' are written in terms
    // of C's stdio. Always included rather than only when one of them is
    // reached -- an unused include costs a program nothing, and asking would
    // mean walking the whole call graph before the first line is written
    out << "#include <cstdio>\n\n";

    emit_forward_declarations();
    emit_types();
    emit_prototypes();
    emit_globals();
    emit_bodies();
    emit_main();

    if (error.size() > 0) {
        return false;
    }

    stream << out.str();

    return true;
}

// Section one. Every type in the program, named and nothing else, so that a
// pointer to one may appear anywhere below without the definition being in
// front of it -- which is most of what Haard allows and C++ does not
void Emitter::emit_forward_declarations() {
    for (u32 i = 0; i < compilation->get_module_count(); i++) {
        Module* module = compilation->get_module(i);
        AstQuery query;

        query.set_module(module);

        for (u32 declaration : query.get_declarations()) {
            AstNodeKind kind = kind_of(i, declaration);

            if (kind != AST_CLASS && kind != AST_STRUCT) {
                continue;
            }

            if (is_generic(i, declaration)) {
                continue;
            }

            u32 candidate = module->get_symbols()->candidate_of(declaration);

            if (candidate == 0) {
                continue;
            }

            out << "struct " << name_of(i, candidate) << ";\n";
        }
    }

    out << "\n";
}

// Section two. A base class and a field held by value have to be complete, so
// the order is a walk over those two edges and not the order the source wrote
void Emitter::emit_types() {
    for (u32 i = 0; i < compilation->get_module_count(); i++) {
        Module* module = compilation->get_module(i);
        AstQuery query;

        query.set_module(module);

        for (u32 declaration : query.get_declarations()) {
            AstNodeKind kind = kind_of(i, declaration);

            if ((kind == AST_CLASS || kind == AST_STRUCT)
                && !is_generic(i, declaration)) {
                emit_type(i, declaration);
            }
        }
    }
}

void Emitter::emit_type(u32 module_index, u32 declaration) {
    Module* module = compilation->get_module(module_index);
    SymbolTable* table = module->get_symbols();
    u32 candidate = table->candidate_of(declaration);
    std::pair<u32, u32> key(module_index, declaration);
    AstQuery query;

    if (candidate == 0 || emitted.count(key) > 0) {
        return;
    }

    // a type that needs itself complete has no size, and emitting it would be
    // a C++ error about a line nobody wrote
    if (emitting.count(key) > 0) {
        fail("'" + text_of(module_index, declaration)
             + "' needs its own definition to be complete");
        return;
    }

    emitting.insert(key);
    query.set_module(module);

    u32 base = table->get_candidate(candidate)->super;
    std::string inherits;

    if (base != INVALID_TYPE) {
        Type* entry = module->get_types()->get_type(base);

        if (entry->kind != TYPE_NAMED) {
            fail("a base that is not a class");
            emitting.erase(key);
            return;
        }

        Module* owner = compilation->get_module(entry->module);
        u32 above = owner->get_symbols()->get_candidate(entry->subject)->ast_node;

        emit_type(entry->module, above);

        inherits = " : public " + name_of(entry->module, entry->subject);
    }

    // and every field held by value, for the same reason the base is
    for (u32 member : query.get_members(declaration)) {
        if (kind_of(module_index, member) != AST_FIELD) {
            continue;
        }

        u32 type = declared_type(module_index, member);

        if (type == INVALID_TYPE) {
            continue;
        }

        Type* entry = module->get_types()->get_type(type);

        if (entry->kind == TYPE_NAMED) {
            Module* owner = compilation->get_module(entry->module);
            u32 held =
                owner->get_symbols()->get_candidate(entry->subject)->ast_node;

            emit_type(entry->module, held);
        }
    }

    emitting.erase(key);
    emitted.insert(key);

    out << "struct " << name_of(module_index, candidate) << inherits << " {\n";
    indentation++;

    for (u32 member : query.get_members(declaration)) {
        if (kind_of(module_index, member) == AST_FIELD) {
            emit_field(module_index, member);
        } else if (kind_of(module_index, member) == AST_FUNCTION) {
            emit_method_declaration(module_index, member);
        }
    }

    emit_structors(module_index, declaration, name_of(module_index, candidate),
                   false);

    indentation--;
    out << "};\n\n";
}

void Emitter::emit_field(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);
    u32 candidate = module->get_symbols()->candidate_of(node);
    AstQuery query;

    if (candidate == 0) {
        return;
    }

    query.set_module(module);

    u32 expression = query.get_binding_expression(node);

    out << std::string(indentation * 4, ' ')
        << declare(module_index, declared_type(module_index, node),
                   name_of(module_index, candidate));

    // Record 0026: a field with no value written is **not initialised**, the
    // way C and C++ leave one, and a field with one is. Writing it here rather
    // than in each constructor is what makes it hold for all of them and for
    // the implicit one a class with no 'init' gets
    if (expression != 0) {
        out << " = ";
        emit_expression(module_index, expression);
    }

    out << ";\n";
}

// Declared inside the class and defined outside it, which is what lets a body
// call anything at all: by the time the bodies are written every prototype is
// in front of them.
//
// Virtual, always. Hadley, 2026-09-02: every method is virtual and there is no
// keyword, so the C++ has to say what the language does not
void Emitter::emit_method_declaration(u32 module, u32 node) {
    u32 candidate = compilation->get_module(module)->get_symbols()
                        ->candidate_of(node);

    if (candidate == 0) {
        return;
    }

    out << std::string(indentation * 4, ' ') << "virtual ";
    emit_signature(module, node, name_of(module, candidate), true);
    out << ";\n";
}

void Emitter::emit_signature(u32 module_index, u32 node,
                             const std::string& name, bool defaults) {
    Module* module = compilation->get_module(module_index);
    SymbolTable* table = module->get_symbols();
    u32 candidate = table->candidate_of(node);
    u32 signature = candidate == 0 ? INVALID_TYPE
                                   : table->get_candidate(candidate)->type;
    AstQuery query;

    if (signature == INVALID_TYPE) {
        fail("a signature that was never built");
        return;
    }

    std::vector<u32> written = module->get_types()->get_arguments(signature);

    query.set_module(module);
    out << type_name(module_index, written.back()) << " " << name;
    emit_parameters(module_index, node, defaults);
}

// 'defaults' is false for a definition written outside its class, because C++
// takes a default argument once and at the declaration -- repeating it is an
// error. Record 0012 makes arity a range, so dropping the default altogether
// would turn a call the language allows into one C++ has no function for
void Emitter::emit_parameters(u32 module_index, u32 node, bool defaults) {
    Module* module = compilation->get_module(module_index);
    AstQuery query;
    std::vector<u32> params;

    query.set_module(module);
    params = query.get_params(node);
    out << "(";

    for (u32 i = 0; i < params.size(); i++) {
        u32 parameter = module->get_symbols()->candidate_of(params[i]);
        u32 value = query.get_binding_expression(params[i]);

        out << (i > 0 ? ", " : "")
            << declare(module_index, declared_type(module_index, params[i]),
                       parameter == 0 ? "" : name_of(module_index, parameter));

        if (defaults && value != 0) {
            out << " = ";
            emit_expression(module_index, value);
        }
    }

    out << ")";
}

// the same list as names alone, for a constructor handing what it was given
// straight to the 'init' that is its body
void Emitter::emit_argument_names(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);
    AstQuery query;
    std::vector<u32> params;

    query.set_module(module);
    params = query.get_params(node);
    out << "(";

    for (u32 i = 0; i < params.size(); i++) {
        u32 parameter = module->get_symbols()->candidate_of(params[i]);

        out << (i > 0 ? ", " : "")
            << (parameter == 0 ? "" : name_of(module_index, parameter));
    }

    out << ")";
}

// Record 0026: the constructor and the destructor are the methods 'init' and
// 'destroy', by convention and not by keyword, so they are emitted **twice**.
// Once as ordinary methods, because they are ordinary methods and 'c.init(5)'
// is a call anyone may write; and once as a C++ constructor and destructor
// whose whole body is a qualified call to them.
//
// Qualified, and that matters: a virtual call from inside a constructor
// reaches the class being built and not the one that will exist, which is a
// C++ trap. Naming the class means the call is exactly the one this class
// wrote, and the base's own constructor has already run its own
void Emitter::emit_structors(u32 module_index, u32 declaration,
                             const std::string& holder, bool bodies) {
    Module* module = compilation->get_module(module_index);
    AstQuery query;

    query.set_module(module);

    for (u32 member : query.get_members(declaration)) {
        if (kind_of(module_index, member) != AST_FUNCTION
            || query.get_declaration_name(member) != "init") {
            continue;
        }

        u32 candidate = module->get_symbols()->candidate_of(member);

        if (candidate == 0) {
            continue;
        }

        if (!bodies) {
            out << std::string(indentation * 4, ' ') << holder;
            emit_parameters(module_index, member, true);
            out << ";\n";
            continue;
        }

        out << holder << "::" << holder;
        emit_parameters(module_index, member, false);
        out << " {\n    this->" << holder << "::"
            << name_of(module_index, candidate);
        emit_argument_names(module_index, member);
        out << ";\n}\n\n";
    }

    // Every class gets one, and it is virtual whether or not the class wrote
    // a 'destroy': a pointer to a base is how a program holds an object, and
    // deleting through one without a virtual destructor runs the wrong code
    // -- silently, and only sometimes
    u32 destroy = 0;

    for (u32 member : query.get_members(declaration)) {
        if (kind_of(module_index, member) == AST_FUNCTION
            && query.get_declaration_name(member) == "destroy") {
            destroy = module->get_symbols()->candidate_of(member);
        }
    }

    // 'copy' is the third of record 0026's family and record 0031's subject:
    // a class that says how to copy itself gets a C++ copy constructor and a
    // copy assignment, both of them a call to it.
    //
    // Assignment destroys first. 'copy' is written as *become a copy of that*,
    // by a class that holds nothing yet, so an assignment has to put the class
    // back into that state before calling it -- and the guard is for 'a = a',
    // which would otherwise free what it is about to read
    u32 copy = 0;

    for (u32 member : query.get_members(declaration)) {
        if (kind_of(module_index, member) == AST_FUNCTION
            && query.get_declaration_name(member) == "copy") {
            copy = module->get_symbols()->candidate_of(member);
        }
    }

    if (!bodies) {
        if (copy != 0) {
            line(holder + "(const " + holder + "& other);");
            line(holder + "& operator=(const " + holder + "& other);");
        }

        line("virtual ~" + holder + "();");
        return;
    }

    if (copy != 0) {
        // const_cast because Haard has no 'const' to write on the parameter
        // (record 0029, deferred), while C++ wants one here or the copy
        // constructor will not bind to a temporary
        std::string call = "this->" + holder + "::"
                         + name_of(module_index, copy) + "(const_cast<"
                         + holder + "&>(other));";

        out << holder << "::" << holder << "(const " << holder
            << "& other) {\n    " << call << "\n}\n\n";

        out << holder << "& " << holder << "::operator=(const " << holder
            << "& other) {\n"
            << "    if (this == &other) {\n        return *this;\n    }\n\n";

        if (destroy != 0) {
            out << "    this->" << holder << "::"
                << name_of(module_index, destroy) << "();\n";
        }

        out << "    " << call << "\n    return *this;\n}\n\n";
    }

    out << holder << "::~" << holder << "() {\n";

    if (destroy != 0) {
        out << "    this->" << holder << "::"
            << name_of(module_index, destroy) << "();\n";
    }

    out << "}\n\n";
}

// Section three. Every free function, so a body may call one written below it
void Emitter::emit_prototypes() {
    for (u32 i = 0; i < compilation->get_module_count(); i++) {
        Module* module = compilation->get_module(i);
        AstQuery query;

        query.set_module(module);

        for (u32 function : query.get_functions()) {
            if (is_generic(i, function)) {
                continue;
            }

            u32 candidate = module->get_symbols()->candidate_of(function);

            if (candidate == 0) {
                continue;
            }

            emit_signature(i, function, name_of(i, candidate), true);
            out << ";\n";
        }
    }

    out << "\n";
}

// Between the prototypes and the bodies, because a global's value may call a
// function and every function is named above by now.
//
// **In source order, and that is a limit worth writing down**: C++ initialises
// what is in one file from the top down, so a global whose value reads another
// declared below it reads that one's zero instead. Haard allows the use, and
// ordering these the way the types are ordered needs a walk over what each
// value reads -- which nothing has asked for yet
void Emitter::emit_globals() {
    for (u32 i = 0; i < compilation->get_module_count(); i++) {
        Module* module = compilation->get_module(i);
        AstQuery query;

        query.set_module(module);

        // the same shape a local has, at no indentation: a 'let' holds
        // bindings and each is one declaration. Sharing emit_binding is what
        // keeps 'a binding becomes a C++ declaration' written once
        for (u32 global : query.get_global_variables()) {
            emit_binding(i, global);
        }
    }

    out << "\n";
}

// Section four. Every body, free functions and methods alike, with nothing
// left that could need something below it
void Emitter::emit_bodies() {
    for (u32 i = 0; i < compilation->get_module_count(); i++) {
        Module* module = compilation->get_module(i);
        AstQuery query;

        query.set_module(module);

        for (u32 function : query.get_functions()) {
            if (is_generic(i, function)) {
                continue;
            }

            emit_function_body(i, function, 0);
        }

        for (u32 declaration : query.get_declarations()) {
            AstNodeKind kind = kind_of(i, declaration);

            if (kind != AST_CLASS && kind != AST_STRUCT
                || is_generic(i, declaration)) {
                continue;
            }

            for (u32 member : query.get_members(declaration)) {
                if (kind_of(i, member) == AST_FUNCTION) {
                    emit_function_body(i, member, declaration);
                }
            }

            u32 candidate = module->get_symbols()->candidate_of(declaration);

            if (candidate != 0) {
                emit_structors(i, declaration, name_of(i, candidate), true);
            }
        }
    }
}

void Emitter::emit_function_body(u32 module_index, u32 node, u32 holder) {
    Module* module = compilation->get_module(module_index);
    SymbolTable* table = module->get_symbols();
    u32 candidate = table->candidate_of(node);
    AstQuery query;
    std::string name;

    if (candidate == 0) {
        return;
    }

    query.set_module(module);
    name = name_of(module_index, candidate);

    if (holder != 0) {
        u32 above = table->candidate_of(holder);

        name = name_of(module_index, above) + "::" + name;
    }

    emit_signature(module_index, node, name, false);
    out << " {\n";
    indentation++;

    std::string native = native_body(module_index, node);

    if (native.size() > 0) {
        out << std::string(indentation * 4, ' ') << native << "\n";
    } else {
        emit_block(module_index, query.get_block(node));
    }

    indentation--;
    out << "}\n\n";
}

// The whole of Haard's input and output, for now: six functions whose bodies
// this writes, because nothing in the language can reach a C library.
//
// It is by NAME and inside the module named 'std.io', which is the cheapest
// thing that works and is meant to be deleted. Record 0030 says why it is not
// a 'native' keyword: a keyword is a language decision, and what the real
// foreign interface looks like has not been taken. The module is half the
// match so that a '__io_write' written anywhere else is an ordinary function
// with an empty body, not something this quietly takes over -- and the same
// trick already finds 'String' in Coercion.
//
// **C's stdio and not C++'s streams**, and the reason is the handle. A 'FILE*'
// is an opaque pointer and is an 'i8*' in Haard with nothing lost; an
// 'std::ofstream' is an object, and Haard cannot name its type, know its size,
// or run its constructor. And 'stdout' is a 'FILE*' too, so one set of
// primitives covers the console and a file alike -- which is what lets a
// 'File' written in Haard print to the terminal.
//
// One character at a time is deliberate. Everything above these six --
// writing a line, a number, a whole file -- is written in Haard, which is the
// point of stopping here.
std::string Emitter::native_body(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);
    AstQuery query;

    if (module->get_name() != "std.io") {
        return "";
    }

    query.set_module(module);

    std::string name = query.get_declaration_name(node);
    std::vector<u32> params = query.get_params(node);
    std::string handle = params.size() > 0
                             ? "(FILE*) " + name_at_param(module_index, params[0])
                             : "";

    // a path and a character are the second thing each of the two takes, and
    // the handle is always the first
    if (name == "__io_open_read" || name == "__io_open_write") {
        return "return (int8_t*) fopen(" + name_at_param(module_index, params[0])
             + ", \"" + (name == "__io_open_read" ? "r" : "w") + "\");";
    }

    // fgetc gives back an int and -1 for the end; the char is what Haard
    // asked for and 'feof' below is the other half of the answer
    if (name == "__io_read") {
        return "return (char) fgetc(" + handle + ");";
    }

    if (name == "__io_at_end") {
        return "return feof(" + handle + ") != 0;";
    }

    if (name == "__io_write") {
        return "fputc(" + name_at_param(module_index, params[1]) + ", "
             + handle + ");";
    }

    if (name == "__io_close") {
        return "fclose(" + handle + ");";
    }

    if (name == "__io_stdout") {
        return "return (int8_t*) stdout;";
    }

    if (name == "__io_stdin") {
        return "return (int8_t*) stdin;";
    }

    if (name == "__io_stderr") {
        return "return (int8_t*) stderr;";
    }

    return "";
}

// the C++ name of a parameter, which is the one thing a written body has to
// agree with the emitted signature about
std::string Emitter::name_at_param(u32 module_index, u32 parameter) {
    Module* module = compilation->get_module(module_index);
    u32 candidate = module->get_symbols()->candidate_of(parameter);

    return candidate == 0 ? "" : name_of(module_index, candidate);
}

// Haard's entry point is a 'def main' of the entry module, which is module 0.
// C++ wants its own signature, so the shim is the one function here that no
// Haard source wrote
void Emitter::emit_main() {
    Module* module = compilation->get_module(0);
    AstQuery query;

    query.set_module(module);

    for (u32 function : query.get_functions()) {
        if (query.get_declaration_name(function) != "main") {
            continue;
        }

        u32 candidate = module->get_symbols()->candidate_of(function);

        if (candidate == 0 || query.get_params(function).size() > 0) {
            continue;
        }

        out << "int main() {\n    return " << name_of(0, candidate)
            << "();\n}\n";

        return;
    }

    fail("the entry module declares no 'main' that takes nothing");
}

void Emitter::emit_block(u32 module, u32 node) {
    if (node == 0) {
        return;
    }

    for (u32 child = child_of(module, node, 0); child != 0;
         child = compilation->get_module(module)->get_ast()
                     ->get_node(child)->get_sibling()) {
        emit_statement(module, child);
    }
}

void Emitter::emit_statement(u32 module, u32 node) {
    switch (kind_of(module, node)) {
    // 'pass' says the block is empty, and an empty block in C++ is written by
    // writing nothing
    case AST_PASS:
        return;

    case AST_BLOCK:
        emit_block(module, node);
        return;

    case AST_IF:
        emit_if(module, node);
        return;

    case AST_WHILE:
        emit_while(module, node);
        return;

    case AST_FOR:
        emit_for(module, node);
        return;

    case AST_LET_DECLARATION:
    case AST_CONST_DECLARATION:
        emit_binding(module, node);
        return;

    // 'a = 1' with no 'a' in sight declares one by being written, and in C++
    // that is a different line from an assignment to something that exists
    case AST_ASSIGNMENT:
        if (compilation->get_module(module)->get_symbols()
                ->candidate_of(node) != 0) {
            out << std::string(indentation * 4, ' ');
            emit_declaring_assignment(module, node);
            out << ";\n";
            return;
        }

        break;

    case AST_RETURN: {
        u32 value = child_of(module, node, 0);

        out << std::string(indentation * 4, ' ') << "return";

        if (value != 0) {
            out << " ";
            emit_expression(module, value);
        }

        out << ";\n";
        return;
    }

    case AST_BREAK:
        line("break;");
        return;

    case AST_CONTINUE:
        line("continue;");
        return;

    case AST_LABEL:
        out << text_of(module, node) << ":;\n";
        return;

    case AST_GOTO:
        line("goto " + text_of(module, child_of(module, node, 0)) + ";");
        return;

    default:
        break;
    }

    // anything else on a line of its own is an expression written for what it
    // does, which is most of the calls a program makes
    out << std::string(indentation * 4, ' ');
    emit_expression(module, node);
    out << ";\n";
}

// 'elif' is 'else if' and that is the whole of the desugaring: the tree keeps
// the three kinds apart because the source spells them apart, and C++ has one
void Emitter::emit_if(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);
    u32 condition = child_of(module_index, node, 0);
    u32 block = child_of(module_index, node, 1);
    u32 next = block == 0
                   ? 0
                   : module->get_ast()->get_node(block)->get_sibling();

    out << std::string(indentation * 4, ' ') << "if (";
    emit_expression(module_index, condition);
    out << ") {\n";
    indentation++;
    emit_block(module_index, block);
    indentation--;
    line("}");

    while (next != 0) {
        AstNodeKind kind = kind_of(module_index, next);

        if (kind == AST_ELIF) {
            u32 inner = child_of(module_index, next, 0);

            out << std::string(indentation * 4, ' ') << "else if (";
            emit_expression(module_index, inner);
            out << ") {\n";
            indentation++;
            emit_block(module_index, child_of(module_index, next, 1));
            indentation--;
            line("}");
        } else if (kind == AST_ELSE) {
            line("else {");
            indentation++;
            emit_block(module_index, child_of(module_index, next, 0));
            indentation--;
            line("}");
        }

        next = module->get_ast()->get_node(next)->get_sibling();
    }
}

void Emitter::emit_while(u32 module, u32 node) {
    out << std::string(indentation * 4, ' ') << "while (";
    emit_expression(module, child_of(module, node, 0));
    out << ") {\n";
    indentation++;
    emit_block(module, child_of(module, node, 1));
    indentation--;
    line("}");
}

// The three parts are always there as nodes even when the source wrote none of
// them -- 'for ; ; :' is a loop that runs forever -- so the two semicolons are
// written unconditionally and each part fills in what it has
void Emitter::emit_for(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);
    AstNodeKind parts[] = { AST_FOR_HEAD, AST_FOR_CONDITION,
                            AST_FOR_INCREMENT };
    u32 block = 0;

    out << std::string(indentation * 4, ' ') << "for (";

    for (u32 which = 0; which < 3; which++) {
        out << (which > 0 ? "; " : "");

        for (u32 part = child_of(module_index, node, 0); part != 0;
             part = module->get_ast()->get_node(part)->get_sibling()) {
            if (kind_of(module_index, part) != parts[which]) {
                continue;
            }

            emit_for_part(module_index, part);
            break;
        }
    }

    for (u32 part = child_of(module_index, node, 0); part != 0;
         part = module->get_ast()->get_node(part)->get_sibling()) {
        if (kind_of(module_index, part) == AST_BLOCK) {
            block = part;
        }
    }

    out << ") {\n";
    indentation++;
    emit_block(module_index, block);
    indentation--;
    line("}");
}

// one part, which holds a list: 'for i = 0, j = n' is two of them
void Emitter::emit_for_part(u32 module_index, u32 part) {
    Module* module = compilation->get_module(module_index);
    u32 written = 0;

    for (u32 inside = child_of(module_index, part, 0); inside != 0;
         inside = module->get_ast()->get_node(inside)->get_sibling()) {
        out << (written > 0 ? ", " : "");

        if (kind_of(module_index, inside) == AST_ASSIGNMENT
            && module->get_symbols()->candidate_of(inside) != 0) {
            // C++ writes one type for a whole declaration list, so a head
            // declaring two things of two types has no shape here. One is the
            // loop everybody writes
            if (written > 0) {
                fail("a 'for' head that declares more than one variable "
                     "cannot be emitted yet");
                return;
            }

            emit_declaring_assignment(module_index, inside);
        } else {
            emit_expression(module_index, inside);
        }

        written++;
    }
}

void Emitter::emit_binding(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);
    AstQuery query;

    query.set_module(module);

    // 'let a, b = 1, 2' is several bindings under one statement
    for (u32 binding = child_of(module_index, node, 0); binding != 0;
         binding = module->get_ast()->get_node(binding)->get_sibling()) {
        u32 candidate = module->get_symbols()->candidate_of(binding);

        if (candidate == 0) {
            fail("a binding that declares nothing");
            return;
        }

        u32 expression = query.get_binding_expression(binding);
        u32 type = module->get_symbols()->get_candidate(candidate)->type;

        // said here rather than left to 'declare', which would only be able to
        // say that some type was never built. A binding with no type is a kind
        // the typer has no answer for yet -- a hash literal, a range, a symbol
        // -- and naming the binding is what points at the line
        if (type == INVALID_TYPE) {
            fail("'" + query.get_declaration_name(binding)
                 + "' has no type the emitter can write");
            return;
        }

        out << std::string(indentation * 4, ' ')
            << declare(module_index, type, name_of(module_index, candidate));

        if (expression != 0) {
            out << " = ";
            emit_expression(module_index, expression);
        }

        out << ";\n";
    }
}

// An assignment that declared by being written. Its left side is not a use, so
// the ResolutionTable has nothing for it -- what it named is on the candidate
// the collector hung on the assignment itself
void Emitter::emit_declaring_assignment(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);
    u32 candidate = module->get_symbols()->candidate_of(node);
    u32 type = module->get_symbols()->get_candidate(candidate)->type;

    if (type == INVALID_TYPE) {
        fail("'" + text_of(module_index, child_of(module_index, node, 0))
             + "' has no type the emitter can write");
        return;
    }

    out << declare(module_index, type, name_of(module_index, candidate))
        << " = ";
    emit_expression(module_index, child_of(module_index, node, 1));
}

void Emitter::emit_expression(u32 module, u32 node) {
    if (node == 0) {
        return;
    }

    switch (kind_of(module, node)) {
    case AST_INTEGER_LITERAL:
    case AST_FLOAT_LITERAL:
    case AST_CHAR_LITERAL:
        out << text_of(module, node);
        return;

    // Haard writes a string with either quote and C++ wants the double one.
    // The bytes between them are the same escapes in both languages
    case AST_STRING_LITERAL: {
        std::string text = text_of(module, node);

        if (text.size() >= 2 && text.front() == '\'') {
            text = "\"" + text.substr(1, text.size() - 2) + "\"";
        }

        out << text;
        return;
    }

    case AST_TRUE:
        out << "true";
        return;

    case AST_FALSE:
        out << "false";
        return;

    case AST_NULL_LITERAL:
        out << "nullptr";
        return;

    case AST_THIS:
        out << "this";
        return;

    case AST_IDENTIFIER:
        emit_identifier(module, node);
        return;

    // '::' carries no text of its own: one child is '::name' and two are
    // 'alias::name', and the name is the last of them either way. The alias
    // and the module name do not survive into the C++ and must not -- what
    // the name means is a declaration in some module, and the mangled name
    // already says which one
    case AST_SCOPE: {
        Ast* ast = compilation->get_module(module)->get_ast();
        u32 first = child_of(module, node, 0);
        u32 second = first == 0 ? 0 : ast->get_node(first)->get_sibling();
        u32 name = second == 0 ? first : second;
        std::string text = name == 0 ? "" : name_at(module, name);

        if (text.size() == 0) {
            fail("a qualified name that names no declaration");
            return;
        }

        out << text;
        return;
    }

    case AST_PARENTHESIS:
        out << "(";
        emit_expression(module, child_of(module, node, 0));
        out << ")";
        return;

    case AST_CALL:
        emit_call(module, node);
        return;

    // record 0018's third coercion: '.' reads a member of a value and of a
    // pointer alike, and C++ does not, so which one is written is a question
    // about the left side's type and not about what the source spelled
    case AST_DOT:
        emit_member(module, node, is_pointer(module, child_of(module, node, 0)));
        return;

    case AST_ARROW:
        emit_member(module, node, true);
        return;

    case AST_INDEX:
        emit_expression(module, child_of(module, node, 0));
        out << "[";
        emit_expression(module, child_of(module, node, 1));
        out << "]";
        return;

    case AST_ASSIGNMENT: emit_binary(module, node, "="); return;
    case AST_PLUS_ASSIGNMENT: emit_binary(module, node, "+="); return;
    case AST_MINUS_ASSIGNMENT: emit_binary(module, node, "-="); return;
    case AST_TIMES_ASSIGNMENT: emit_binary(module, node, "*="); return;
    case AST_DIVISION_ASSIGNMENT: emit_binary(module, node, "/="); return;
    case AST_MODULO_ASSIGNMENT: emit_binary(module, node, "%="); return;
    case AST_BITWISE_AND_ASSIGNMENT: emit_binary(module, node, "&="); return;
    case AST_BITWISE_OR_ASSIGNMENT: emit_binary(module, node, "|="); return;
    case AST_BITWISE_XOR_ASSIGNMENT: emit_binary(module, node, "^="); return;
    case AST_BITWISE_LEFT_SHIFT_ASSIGNMENT:
        emit_binary(module, node, "<<="); return;
    case AST_BITWISE_RIGHT_SHIFT_ASSIGNMENT:
        emit_binary(module, node, ">>="); return;

    case AST_PLUS: emit_binary(module, node, "+"); return;
    case AST_MINUS: emit_binary(module, node, "-"); return;
    case AST_TIMES: emit_binary(module, node, "*"); return;
    case AST_DIVISION: emit_binary(module, node, "/"); return;
    case AST_MODULO: emit_binary(module, node, "%"); return;

    // both spellings of each, because the tree keeps them apart and C++ has
    // one of each
    case AST_LOGICAL_AND: emit_binary(module, node, "&&"); return;
    case AST_LOGICAL_OR: emit_binary(module, node, "||"); return;
    case AST_LOGICAL_NOT:
    case AST_LOGICAL_NOT_OPERATOR: emit_unary(module, node, "!"); return;

    case AST_EQUAL: emit_binary(module, node, "=="); return;
    case AST_NOT_EQUAL: emit_binary(module, node, "!="); return;
    case AST_LESS_THAN: emit_binary(module, node, "<"); return;
    case AST_GREATER_THAN: emit_binary(module, node, ">"); return;
    case AST_LESS_THAN_OR_EQUAL: emit_binary(module, node, "<="); return;
    case AST_GREATER_THAN_OR_EQUAL: emit_binary(module, node, ">="); return;

    case AST_BITWISE_AND: emit_binary(module, node, "&"); return;
    case AST_BITWISE_OR: emit_binary(module, node, "|"); return;
    case AST_BITWISE_XOR: emit_binary(module, node, "^"); return;
    case AST_BITWISE_LEFT_SHIFT: emit_binary(module, node, "<<"); return;
    case AST_BITWISE_RIGHT_SHIFT: emit_binary(module, node, ">>"); return;

    case AST_UNARY_MINUS: emit_unary(module, node, "-"); return;
    case AST_UNARY_PLUS: emit_unary(module, node, "+"); return;
    case AST_BITWISE_NOT: emit_unary(module, node, "~"); return;
    case AST_ADDRESS_OF: emit_unary(module, node, "&"); return;
    case AST_DEREFERENCE: emit_unary(module, node, "*"); return;
    case AST_PRE_INCREMENT: emit_unary(module, node, "++"); return;
    case AST_PRE_DECREMENT: emit_unary(module, node, "--"); return;
    case AST_POST_INCREMENT: emit_postfix(module, node, "++"); return;
    case AST_POST_DECREMENT: emit_postfix(module, node, "--"); return;

    case AST_SIZEOF:
        out << "sizeof(" << type_name(module, type_at(module,
                                          child_of(module, node, 0))) << ")";
        return;

    case AST_CAST:
        out << "(" << type_name(module, type_at(module, node)) << ")(";
        emit_expression(module, child_of(module, node, 0));
        out << ")";
        return;

    // record 0026: the arguments are the 'init' the type phase chose, and C++
    // reaches it the same way -- the constructor this emitter wrote for that
    // 'init' has the same parameters
    // the type node under a 'new' is a type and not an expression, so it is
    // not in the ResolutionTable at all. What is there is the 'new' itself,
    // which the typer answered with a pointer to what was made
    case AST_NEW: {
        u32 made = type_at(module, node);
        TypeTable* types = compilation->get_module(module)->get_types();
        Type* entry = types->get_type(made);

        if (made == INVALID_TYPE || entry->kind != TYPE_POINTER) {
            fail("a 'new' whose type was never built");
            return;
        }

        out << "new "
            << type_name(module, types->get_argument(entry->first_argument));

        // 'new T[n]' -- and the length is read off the TREE and not off the
        // type, because that is the only place it survives. A type is a value,
        // so a length that is not a literal cannot be one (TypeBuilder gives
        // it NO_LENGTH); the expression that wrote it is still a child of the
        // type node, and here it is an ordinary expression like any other.
        //
        // So a non-literal length works, and it works without agenda 5.3's
        // constant evaluation, which is about a length inside a **type**
        u32 written = child_of(module, node, 0);

        if (kind_of(module, written) == AST_ARRAY_TYPE) {
            u32 length = child_of(module, written, 1);

            out << "[";

            if (length != 0) {
                emit_expression(module, length);
            }

            out << "]";
            return;
        }

        emit_call_arguments(module, second_child_of(module, node));
        return;
    }

    case AST_DELETE:
        out << "delete ";
        emit_expression(module, child_of(module, node, 0));
        return;

    case AST_DELETE_ARRAY:
        out << "delete[] ";
        emit_expression(module, child_of(module, node, 0));
        return;

    default:
        break;
    }

    fail("this expression cannot be emitted yet");
}

void Emitter::emit_binary(u32 module, u32 node, const std::string& oper) {
    emit_expression(module, child_of(module, node, 0));
    out << " " << oper << " ";
    emit_expression(module, child_of(module, node, 1));
}

void Emitter::emit_unary(u32 module, u32 node, const std::string& oper) {
    out << oper;
    emit_expression(module, child_of(module, node, 0));
}

void Emitter::emit_postfix(u32 module, u32 node, const std::string& oper) {
    emit_expression(module, child_of(module, node, 0));
    out << oper;
}

void Emitter::emit_member(u32 module, u32 node, bool arrow) {
    emit_expression(module, child_of(module, node, 0));
    out << (arrow ? "->" : ".");

    u32 right = child_of(module, node, 1);
    std::string name = name_at(module, right);

    out << (name.size() > 0 ? name : text_of(module, right));
}

// A bare name that means a field or a method of the class the code is inside
// -- its own or a base's, record 0020 -- has to be written 'this->' in C++,
// which has no such lookup for a member from a free position
void Emitter::emit_identifier(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);
    Resolution* found = module->get_resolutions()->get(node);
    std::string name = name_at(module_index, node);

    if (name.size() == 0) {
        fail("'" + text_of(module_index, node) + "' names no declaration");
        return;
    }

    if (found->module == module_index) {
        SymbolKind kind = (SymbolKind) module->get_symbols()
                              ->get_candidate(found->candidate)->kind;

        if (kind == SYMBOL_FIELD
            || (kind == SYMBOL_FUNCTION
                && holder_of(module_index, found->candidate) != 0)) {
            out << "this->";
        }
    }

    out << name;
}

void Emitter::emit_call(u32 module_index, u32 node) {
    emit_expression(module_index, child_of(module_index, node, 0));
    emit_call_arguments(module_index, child_of(module_index, node, 1));
}

void Emitter::emit_call_arguments(u32 module_index, u32 arguments) {
    Module* module = compilation->get_module(module_index);
    u32 written = 0;

    out << "(";

    for (u32 argument = arguments == 0
                            ? 0
                            : child_of(module_index, arguments, 0);
         argument != 0;
         argument = module->get_ast()->get_node(argument)->get_sibling()) {
        out << (written > 0 ? ", " : "");
        emit_expression(module_index, argument);
        written++;
    }

    out << ")";
}

u32 Emitter::second_child_of(u32 module, u32 node) {
    return child_of(module, node, 1);
}

std::string Emitter::name_of(u32 module, u32 candidate) {
    Module* owner = compilation->get_module(module);
    Candidate* found = owner->get_symbols()->get_candidate(candidate);
    AstQuery query;
    std::string source;
    std::string clean;

    query.set_module(owner);

    // the declaration's name and not its token: a function's token is the
    // 'def' that opened it, which every function in the program shares
    source = query.get_declaration_name(found->ast_node);

    if (source.size() == 0) {
        source = std::string(owner->get_token_value(
            owner->get_ast()->get_node(found->ast_node)->get_token()));
    }

    // the source name is carried only so a reader of the C++ can find their
    // way back; what makes the name unique is the two indices in front of it
    for (char letter : source) {
        clean += (letter >= 'a' && letter <= 'z')
                      || (letter >= 'A' && letter <= 'Z')
                      || (letter >= '0' && letter <= '9')
                  ? letter
                  : '_';
    }

    // A **method** is named by what makes it one method and not another, which
    // record 0020 already says: its own name and its parameters. Two classes
    // in a chain writing the same pair are the same method written twice, and
    // in C++ they have to carry the same name or the derived one declares a
    // second virtual function instead of overriding the first -- which
    // compiles, runs, and calls the wrong body.
    //
    // Nothing else is needed to make it unique: a method lives inside its
    // struct, so two unrelated classes may both have one, and two in the same
    // class with the same parameters are record 0012's ambiguity and already
    // an error.
    if (holder_of(module, candidate) != 0) {
        return "m_" + clean + mangle_parameters(module, candidate);
    }

    // everything else is named by where it is declared. Record 0010 puts two
    // versions of one library in one program, so the source name is not unique
    // and the two indices are what make it so
    return "h" + std::to_string(module) + "_" + std::to_string(candidate) + "_"
         + clean;
}

// The parameters of a method, as a string that is the same in every module
// that can see them. It has to be: a base in one module and a derived in
// another must agree, and a type index does not cross a module boundary while
// the pair a named type carries -- record 0016 writes the module down -- does
std::string Emitter::mangle_parameters(u32 module_index, u32 candidate) {
    Module* module = compilation->get_module(module_index);
    u32 signature = module->get_symbols()->get_candidate(candidate)->type;
    std::string out;

    if (signature == INVALID_TYPE) {
        return "";
    }

    std::vector<u32> written = module->get_types()->get_arguments(signature);

    // the return is the last one and record 0012 keeps it out of what makes
    // two overloads different, so it is out of the name too -- which is also
    // what lets record 0020's covariant return work
    written.pop_back();

    for (u32 parameter : written) {
        out += "_" + mangle_type(module_index, parameter);
    }

    return out;
}

std::string Emitter::mangle_type(u32 module_index, u32 type) {
    if (type == INVALID_TYPE) {
        return "x";
    }

    TypeTable* types = compilation->get_module(module_index)->get_types();
    Type* entry = types->get_type(type);
    u32 inside = entry->argument_count > 0
                     ? types->get_argument(entry->first_argument)
                     : INVALID_TYPE;

    switch ((TypeKind) entry->kind) {
    case TYPE_BUILTIN:
        return "b" + std::to_string(entry->subject);

    case TYPE_NAMED:
        return "n" + std::to_string(entry->module) + "c"
             + std::to_string(entry->subject);

    case TYPE_POINTER:
        return "p" + mangle_type(module_index, inside);

    case TYPE_REFERENCE:
        return "r" + mangle_type(module_index, inside);

    case TYPE_ARRAY:
        return "a" + std::to_string(entry->subject)
             + mangle_type(module_index, inside);

    default:
        break;
    }

    return "x";
}

std::string Emitter::name_at(u32 module, u32 node) {
    Resolution* found =
        compilation->get_module(module)->get_resolutions()->get(node);

    if (found->candidate == 0) {
        return "";
    }

    return name_of(found->module, found->candidate);
}

std::string Emitter::type_name(u32 module, u32 type) {
    return declare(module, type, "");
}

// One string and not two, because C++ writes an array's length after the name
// it belongs to. Everything that declares anything goes through here
std::string Emitter::declare(u32 module_index, u32 type,
                             const std::string& name) {
    std::string tail = name.size() > 0 ? " " + name : "";

    if (type == INVALID_TYPE) {
        fail("a type that was never built");
        return "void" + tail;
    }

    Module* module = compilation->get_module(module_index);
    TypeTable* types = module->get_types();
    Type* entry = types->get_type(type);
    u32 inside = entry->argument_count > 0
                     ? types->get_argument(entry->first_argument)
                     : INVALID_TYPE;

    switch ((TypeKind) entry->kind) {
    case TYPE_BUILTIN:
        return std::string(entry->subject < BUILTIN_COUNT
                               ? BUILTIN_CPP[entry->subject]
                               : "void") + tail;

    case TYPE_NAMED:
        return name_of(entry->module, entry->subject) + tail;

    case TYPE_POINTER:
        return declare(module_index, inside, "*" + name);

    case TYPE_REFERENCE:
        return declare(module_index, inside, "&" + name);

    case TYPE_ARRAY:
        if (entry->subject == NO_LENGTH) {
            fail("an array with no length cannot be emitted yet");
            return "void" + tail;
        }

        return declare(module_index, inside,
                       name + "[" + std::to_string(entry->subject) + "]");

    default:
        break;
    }

    fail("this type cannot be emitted yet");

    return "void" + tail;
}

u32 Emitter::holder_of(u32 module_index, u32 candidate) {
    Module* module = compilation->get_module(module_index);
    SymbolTable* table = module->get_symbols();
    u32 inside = table->scope_owned_by(
        table->get_candidate(candidate)->ast_node);

    if (inside == 0) {
        return 0;
    }

    u32 around = table->get_scope(inside)->parent;

    return around == 0 ? 0 : table->get_scope(around)->owner;
}

bool Emitter::is_pointer(u32 module, u32 node) {
    u32 type = type_at(module, node);

    if (type == INVALID_TYPE) {
        return false;
    }

    return compilation->get_module(module)->get_types()->get_type(type)->kind
        == TYPE_POINTER;
}

u32 Emitter::type_at(u32 module, u32 node) {
    return compilation->get_module(module)->get_resolutions()->get(node)->type;
}

// The type a **declaration** was given, which is not the same table: the
// ResolutionTable is indexed by node and holds what an *expression* turned out
// to be, while a field, a parameter and a binding carry theirs on the
// candidate the collector filled
u32 Emitter::declared_type(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);
    u32 candidate = module->get_symbols()->candidate_of(node);

    return candidate == 0
               ? INVALID_TYPE
               : module->get_symbols()->get_candidate(candidate)->type;
}

AstNodeKind Emitter::kind_of(u32 module, u32 node) {
    return (AstNodeKind) compilation->get_module(module)->get_ast()
        ->get_node(node)->get_kind();
}

u32 Emitter::child_of(u32 module_index, u32 node, u32 which) {
    Ast* ast = compilation->get_module(module_index)->get_ast();
    u32 child = ast->get_node(node)->get_children();

    while (child != 0 && which > 0) {
        child = ast->get_node(child)->get_sibling();
        which--;
    }

    return child;
}

std::string Emitter::text_of(u32 module_index, u32 node) {
    Module* module = compilation->get_module(module_index);

    return std::string(module->get_token_value(
        module->get_ast()->get_node(node)->get_token()));
}

void Emitter::line(const std::string& text) {
    out << std::string(indentation * 4, ' ') << text << '\n';
}
